      --   width = 40,
      --   side = "left",
      --   open_icon = "▾",
      --   close_icon = "▸",
      --   telescope = {
      --     initial_mode = "normal",
      --     layout_strategy = "horizontal",
      --     prompt_title = "Vista",
      --     prompt_prefix = "❯ ",
      --     preview_title = "Preview",
      --   },
      -- })

